import Providers from "@/components/Providers";
import "./globals.css";

export const metadata = {
  title: "Next.js Realtime Chat Application",
  description:
    "Generated by create next app, Next.js Realtime Chat Application",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
